### ISSUE TITLE
Bump curl to 8.4.0 or later

### ISSUE THREAD

**Issue by licaon-kter** [supertuxkart/dependencies#7]
ref: https://curl.se/docs/CVE-2023-38545.html

**Comment by licaon-kter** [comment]
any news?

**Comment by licaon-kter** [comment]
@deveee will see, just remember https://github.com/supertuxkart/dependencies/issues/6 :)

**Comment by nutzboi** [comment]
> ~~Next beta packages will be built with updated curl.~~

~~SuperTuxKart 1.5-rc1 and 1.5 came out, still with curl 8.1.2-DEV and there is no dependencies build release :(~~

~~My interest in newly updated dependencies (specifically with new cURL) comes from ``/installaddon`` failing for gamebanana links on platforms where [old] cURL is packaged with the game like Windows and Android.
Although for Windows, I just replace the DLL in the game dir so I'm fine there.~~

turns out it was an issue with stk-code/data/cacert.pem.
